zeus-config-service:
  api:
    version: 1.0.0
server:
  port: 8091
spring:
  profiles:
    active: clean, local
logging:
  file:
    name: logs/local/config-service.log
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
